[package]
name = "axon_core"
version = "0.1.0"
edition = "2024"

[dependencies]
android_logger = "0.15.1"
artiqwest = "0.4.0"
axum = "0.8.9"
env_logger = "0.11.11"
fast-socks5 = "1.0.0"
ipstack = "1.0.1"
log = "0.4.33"
reqwest = { version = "0.13.4", features = ["json", "socks"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tun = { version = "0.8.14", features = ["async"] }
